from .audio import Ui_audioOp
from .crop import Ui_cropOp
from .insert import Ui_insertOp
from .noop import Ui_noOp
from .pace import Ui_paceOp
from .prefs import Ui_prefsDialog
from .prog import Ui_progDialog
from .render import Ui_renderOp
from .optab import Ui_opsWidget
from .section import Ui_sectionOp
from .text import Ui_textOp
from .window import Ui_MainWindow
from .shell import Ui_shellOp
from .window import Ui_MainWindow